### ISSUE TITLE
Validation des emails : mismatch entre front et back, cause server error

### ISSUE THREAD

**Issue by estellecomment** [betagouv/e-controle#121]
![image](https://user-images.githubusercontent.com/911434/57696495-2bc0e080-7651-11e9-93d1-0723c1f6f4a0.png)

La validation des emails sur le front end est plus permissive que celle sur le back end.
Du coup, on peut entrer un email erroné qui passe la validation du front, et ensuite fait un server error. 
Ce server error est incompréhensible pour l'utilisateur.

Solution : durcir la validation des emails sur le front, pour qu'elle soit la même que sur le back.

**Comment by LeryJ** [comment]
Cas trop particulier et l'erreur du back est suffisante
