### ISSUE TITLE
Quand une personne a été retirée d'un contrôle, elle parvient à se reconnecter mais la page e-contrôle est vierge

### ISSUE THREAD

**Issue by LeryJ** [betagouv/e-controle#148]
L'utilisateur aura une page d'accueil vierge sans explication.

![Capture](https://user-images.githubusercontent.com/43180136/58963283-2caae500-87ad-11e9-897b-5ab00bd92a3d.PNG)

**Comment by estellecomment** [comment]
on peut afficher un message qui explique la situation : "vous n'avez acces a aucun controle" 
et un message qui propose une piste pour resoudre le probleme : "contactez l'equipe de controle pour avoir acces"

**Comment by LeryJ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [df](https://trello.com/c/6ILTG6Ep/514-df)
