### ISSUE TITLE
En tant que contrôleur, je ne sais pas si la personne ajoutée a reçu l'information qu'il a désormais accès à e-contrôle

### ISSUE THREAD

**Issue by LeryJ** [betagouv/e-controle#150]
Lors de l’envoi du lien de connexion à l’équipe de contrôle, serait-il possible de prévoir un court texte d’accompagnement précisant qu’il appartient à l’équipe de contrôle de communiquer la procédure d’accès au contrôlé + un court message type décrivant la procédure de connexion pour le contrôlé.

**Comment by LeryJ** [comment]
Suggestion d'un utilisateur : 
- Quand on valide l'ajout d'une personne, on nous propose d'envoyer "une invitation personnalisée comme sur LinkedIn"

**Comment by estellecomment** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [das](https://trello.com/c/dmu95k7U/474-das)

**Comment by LeryJ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Maquette "informer qu'il faut envoyer un email"](https://trello.com/c/VtlrZ6m8/476-maquette-informer-quil-faut-envoyer-un-email)

**Comment by LeryJ** [comment]
En PROD V0.11
