### ISSUE TITLE
Quand les numeros de questions ont 4 chiffres, ils debordent et ne sont pas affiches

### ISSUE THREAD

**Issue by estellecomment** [betagouv/e-controle#164]
![image](https://user-images.githubusercontent.com/911434/59849873-239f4380-9369-11e9-8d93-f5dfd6544d82.png)

**Comment by estellecomment** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue #164 : les numeros de questions a 4 chiffres debordent](https://trello.com/c/0FbaDN2d/462-issue-164-les-numeros-de-questions-a-4-chiffres-debordent)

**Comment by estellecomment** [comment]
Chez moi, sur macos avec chrome et firefox, le probleme n'apparait pas. Je cherche à le reproduire.

@LeryJ tu es sur quel navigateur?

**Comment by LeryJ** [comment]
Mozzila et Edge

**Comment by LeryJ** [comment]
![image](https://user-images.githubusercontent.com/43180136/60520035-f9447300-9ce4-11e9-8ecd-f25cdabf9d81.png)

**Comment by LeryJ** [comment]
Résolu en PPROD sur IE et compagnie

**Comment by estellecomment** [comment]
tant mieux! Comment?

**Comment by LeryJ** [comment]
J’ai testé et ça n’affichait plus le bug.
Ce n’est pas toi qui l’a résolu (dans le code) ?

[cid:image002.png@01D30AE8.15260520]



Léry JICQUEL
Intrapreneur de startup d’Etat
Secrétariat général
Cour des comptes
T 01 42 98 97 28
www.ccomptes.fr<http://www.ccomptes.fr/>



De : Estelle Comment <notifications@github.com>
Envoyé : lundi 8 juillet 2019 11:01
À : betagouv/e-controle <e-controle@noreply.github.com>
Cc : Jicquel, Lery <lery.jicquel@ccomptes.fr>; State change <state_change@noreply.github.com>
Objet : Re: [betagouv/e-controle] Quand les numeros de questions ont 4 chiffres, ils debordent et ne sont pas affiches (#164)


tant mieux! Comment?
