### ISSUE TITLE
En tant que contrôlé, je ne peux pas déposer plusieurs fichiers dont le volume global est supérieur à 256Mo.

### ISSUE THREAD

**Issue by LeryJ** [betagouv/e-controle#193]
Message reçu : 

E-control fonctionne bien mais au final notre interlocuteur  n’a pas pu déposer les fichiers les plus volumineux (y compris celui inférieur à 256 Mo, son chargement s’est perdu en cours de route, mais peut-être un problème de réseau chez eux ?).
Au final, la solution trouvée pour éviter un WeTransfer a été d’utiliser correspondancejf qui, lui, a accepté tous les fichiers….
 
En fait c’est presque la capacité d’un DVD entier que notre interlocuteur a déposé (4,2Go) !!!
Ne reste plus qu’à télécharger ces fichiers, ce qui pourrait prendre la nuit vu notre débit (firefox indique environ 6h de téléchargement) ….
Pour la suite du contrôle nous souhaiterions bien sûr poursuivre l’aventure avec l’outil e-control en espérant ne pas recevoir autant de données à chaque questionnaire.
Je reste à disposition pour toute question,

**Comment by estellecomment** [comment]
Les fichiers de plus de 256M sont maintenant bloqués avec une belle erreur compréhensible.

Je viens de déposer 5 fichiers de 100M en même temps en pprod, ca marche.
Donc je pense que c'est un problème de réseau trop lent de leur part. On a améliorer aussi les erreurs pour le timeout, c'est compréhensible.

Je ferme.
