### ISSUE TITLE
En tant que contrôleur, si j'indique un nom cour avec des . des / ou des * ça ne créé pas de fichiers webdav

### ISSUE THREAD

**Issue by LeryJ** [betagouv/e-controle#227]

**Comment by LeryJ** [comment]
J'ai crée un espace de dépôt.
Pour ne nom court j'ai mis "02/08/2019". 
J'ai validé.
Le fichier n'était pas accessible dans webdav. Je n'ai pas de message d'erreur

**Comment by LeryJ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Champs code de référence sans / . ; ...](https://trello.com/c/4yuxh0Dy/576-champs-code-de-r%C3%A9f%C3%A9rence-sans)

**Comment by estellecomment** [comment]
Fixé par les PRs https://github.com/betagouv/e-controle/pull/232 et https://github.com/betagouv/e-controle/pull/233
