### ISSUE TITLE
Validation d'un questionnaire brouillon par erreur

### ISSUE THREAD

**Issue by LeryJ** [betagouv/e-controle#249]
Contexte : 

2 collègues ont validé des brouillons par erreur.
Elles ne peuvent plus faire marche arrière.
Conséquence: le questionnaire est visible par le contrôlé alors qu'il n'est pas véritablement terminé.

Solution : 

L'équipe e.contrôle prend la main à distance pour cocher brouillon et donner le bon statut à ces questionnaire non définitif.

**Comment by estellecomment** [comment]
Je pense que la publication du questionnaire ne devrait pas etre dans le flow de creation de brouillon. 

La creation du brouillon est une tâche, la publication en est une autre : les deux ne se font pas au même moment (parce qu'il y a une etape de consultation entre collegues entre les deux).

Je pense qu'il faut deplacer le bouton Publier à la page de liste des espaces : 
![Screenshot 2019-09-02 at 14 06 04](https://user-images.githubusercontent.com/911434/64113544-e56fc880-cd8a-11e9-8af4-3df0dc9094c8.png)

**Comment by estellecomment** [comment]
Doublon de https://github.com/betagouv/e-controle/issues/230. Je ferme 230.

**Comment by LeryJ** [comment]
Depuis plusieurs semaines, personne ne m'a fait remonter ce problème. je close
