### ISSUE TITLE
Probleme de perte de modifications

### ISSUE THREAD

**Issue by LeryJ** [betagouv/e-controle#272]
17 sep 2019 : probleme de perte de modifications - Post mortem

Logs d’acces pour le questionnaire 203
13h20 a 14h29 :  -> la verif Catherine travaille
14h30-14h39 :  -> la magistrate Line va valider, et se rend compte qu’il manque des modifs
14h40-14h49 : 1 -> elles en discutent ensemble
14h50 - 14h59 : plus personne

Explication (possible) de l’incident :  
Mardi matin, Catherine et magistrate ont la page ouverte et voient la meme version.
Mardi 13h30, Catherine fait des modifs, puis ferme son navigateur a 14h30
Mardi 14h50, Line reprend sa page ouverte, ou l’ancienne version est toujours affichee. Sans rafraichir la page, elle clique sur suivant. L’auto-save enregistre ce qui est dans son browser, c’est a dire l’ancienne version.
Catherine rouvre son browser, et voit l’ancienne version.

Solution immediate : 
Pusher en prod des que possible une modif, qui limite l’acces a l’edition de Brouillons : seul l’utilisateur qui a créé le brouillon (premiere sauvegarde en memoire) peut acceder. Pour les autres, la page n’apparait pas.
On ajoute un message d’info au dessus de la page d’edition de brouillons, qui explique que l’acces a ete temporairement supprimé a certains utilisateurs.

Option bis :
L’éditeur peut modif et voir
Les autres ont juste accès aux brouillons word ?

Solution long-terme : 
On reimplemente l’edition collaborative proprement, je sais pas encore comment :)

https://docs.google.com/document/d/1F_P8dO0Rzt3o-7BCiQpp8GxhnxkJHvzDSV1tMU-CuOw/edit

**Comment by estellecomment** [comment]
Fixé en désactivant l'édition collaborative. Je ferme.
