### ISSUE TITLE
Après avoir publié mon questionnaire, les questions ont disparu.

### ISSUE THREAD

**Issue by LeryJ** [betagouv/e-controle#289]
Une collègue a préparé un questionnaire X (brouillon).
Elle demande à la magistrate de donner son avis qui lui dit que c'est ok.
La collègue le publie et demande à l'organisme de déposer des réponses.
Durant cette période, il y a eu de nombreux bugs d'accès à internet dans cette CRC.

L'organisme informe qu'il n'y a pas de questions dans le questionnaire.

La collègue refait donc un nouveau questionnaire.

**Comment by estellecomment** [comment]
Sans plus de détails on ne peut pas le résoudre. Je ferme.
