### ISSUE TITLE
En tant que contrôleur/admin, je ne peux pas supprimer un espace de dépôt

### ISSUE THREAD

**Issue by LeryJ** [betagouv/e-controle#302]
Une contrôleuse nous demande par email de clôturer un espace de dépôt.

J'ai testé en PPROD et ce n'est pas possible car ça supprimerait les actions. Les droits d'admin ne nous l'autorise pas.

Solution alternative:
- Pour les utilisateurs : les retirer de cet espace de dépôt

Pas de solutions à court terme pour vraiment le supprimer.

**Comment by estellecomment** [comment]
Solution : soft-delete ("désactiver"). Pas encore implémenté.

**Comment by estellecomment** [comment]
Implémenté
