### ISSUE TITLE
En tant que contrôleur, je n'ai pas renommé le bon espace de dépôt

### ISSUE THREAD

**Issue by LeryJ** [betagouv/e-controle#348]
Une collègue avait créé deux espaces de dépôt.
On lui a demandé de ne faire qu'un seul contrôle avec e.contrôle finalement.
Elle a renommé un espace de dépôt avant l'existence de la sidebar mais ce n'était pas le bon.
Bilan :
- le nom de l'espace et le nom du code de référence ne sont pas concordant.
- Avec la sidebar, c'est visible pour elle et le contrôlé.

Le contrôle est terminé donc sans gravité.

Solution : 
- indiquer le code de référence dans le champs "modifier l'espace de dépôt"

**Comment by estellecomment** [comment]
solved by https://github.com/betagouv/e-controle/pull/360
