### ISSUE TITLE
En tant que contrôleur, je ne vois pas les questionnaires "brouillons" dans le menu de gauche sur IE uniquement

### ISSUE THREAD

**Issue by LeryJ** [betagouv/e-controle#418]
En réalisant la recette V1.11, j'ai aperçu cette anomalie :

En tant que contrôleur, je ne vois pas les questionnaires "brouillons" dans le menu de gauche sur IE uniquement

L'impact est faible et non bloquant.

**Comment by estellecomment** [comment]
Résolu par https://github.com/betagouv/e-controle/pull/423
